name: test-coverage

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read


jobs:
  coverage:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Run coverage
        run: go test -coverprofile=coverage.out -coverpkg=./... ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
